### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by supirhero** [dasilvacontin/ag-drift#34]

**Comment by dasilvacontin** [comment]
@supirhero Sorry! Haven't seen this until now. Cloning the repo and running `npm install && npm start` should locally host the game and have it ready at `http://localhost:3000`.

Still, I recommend playing the online version on Heroku at https://ag-drift.herokuapp.com/. It might take 10 seconds to load due to Heroku having to boot up if no one was playing recently (which is likely the case).

Let me know if that didn't solve your doubts, welcome to ask anything else! Cheers!
